
package cn.iverson.bos.ws.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import cn.iverson.bos.ws.ObjectFactory;
import cn.iverson.bos.ws.Waybilldetail;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWaybillWs", targetNamespace = "http://ws.bos.iverson.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWaybillWs {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.iverson.bos.ws.Waybilldetail>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "waybilldetailList", targetNamespace = "http://ws.bos.iverson.cn/", className = "cn.iverson.bos.ws.WaybilldetailList")
    @ResponseWrapper(localName = "waybilldetailListResponse", targetNamespace = "http://ws.bos.iverson.cn/", className = "cn.iverson.bos.ws.WaybilldetailListResponse")
    public List<Waybilldetail> waybilldetailList(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addWaybill", targetNamespace = "http://ws.bos.iverson.cn/", className = "cn.iverson.bos.ws.AddWaybill")
    @ResponseWrapper(localName = "addWaybillResponse", targetNamespace = "http://ws.bos.iverson.cn/", className = "cn.iverson.bos.ws.AddWaybillResponse")
    public Long addWaybill(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

}
